Repository laravelcm/laravel.cm, pull requests merged in 2024-12, with the labels that each got.

#239 translate privacy page
  lang/en/pages/privacy.php
  lang/fr/pages/privacy.php
  resources/views/privacy.blade.php
Labels: i18n, front

#238 translate terms page
  lang/en/pages/terms.php
  lang/fr/pages/terms.php
  resources/views/terms.blade.php
Labels: i18n, front

#236 Feature/lar 111 create edit discussion
  app/Actions/Discussion/ConvertDiscussionToThreadAction.php
  app/Actions/Discussion/CreateOrUpdateDiscussionAction.php
  app/Actions/Discussion/NotifyUsersOfThreadConversion.php
  app/Livewire/Components/Slideovers/DiscussionForm.php
  app/Livewire/Discussions/Create.php
  app/Livewire/Discussions/Edit.php
  app/Livewire/Discussions/Subscribe.php
  app/Livewire/Modals/ConvertDiscussion.php
  app/Livewire/Modals/Unsplash.php
  app/Livewire/NotificationIndicator.php
  app/Livewire/Pages/Discussions/SingleDiscussion.php
  app/Policies/DiscussionPolicy.php
  app/Providers/AppServiceProvider.php
  app/Traits/WithTagsAssociation.php
  composer.json
  composer.lock
  lang/en/actions.php
  lang/en/notifications.php
  lang/en/pages/discussion.php
  lang/fr/actions.php
  lang/fr/notifications.php
  lang/fr/pages/discussion.php
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
  public/js/filament/filament/echo.js
  public/js/filament/forms/components/file-upload.js
  public/js/filament/forms/components/rich-editor.js
  public/js/filament/support/support.js
  public/js/filament/tables/tables.js
  resources/views/components/launch-content.blade.php
  resources/views/components/user/breadcrumb.blade.php
  resources/views/livewire/components/slideovers/discussion-form.blade.php
  resources/views/livewire/discussions/_form.blade.php
  resources/views/livewire/discussions/create.blade.php
  resources/views/livewire/discussions/edit.blade.php
  resources/views/livewire/discussions/subscribe.blade.php
  resources/views/livewire/modals/convert-discussion.blade.php
  resources/views/livewire/notification-indicator.blade.php
  resources/views/livewire/notifications-page.blade.php
  resources/views/livewire/pages/discussions/index.blade.php
  resources/views/livewire/pages/discussions/single-discussion.blade.php
  resources/views/user/notifications.blade.php
  routes/features/discussion.php
  routes/web.php
  tests/CreatesUsers.php
  tests/Feature/Commands/DeleteOldUnverifiedUsersTest.php
  tests/Feature/Commands/PostArticleToTwitterTest.php
  tests/Feature/Livewire/Components/Slideovers/DiscussionFormTest.php
  tests/Feature/Livewire/Components/Slideovers/ThreadFormTest.php
  tests/Feature/Livewire/DiscussionTest.php
  tests/Feature/Livewire/Modal/ConvertDiscussionTest.php
  tests/Feature/Livewire/Pages/Auth/AuthenticationTest.php
  tests/Feature/Livewire/Pages/Auth/EmailVerificationTest.php
  tests/Feature/Livewire/Pages/Auth/PasswordResetTest.php
  tests/Feature/Livewire/Pages/Auth/PasswordUpdateTest.php
  tests/Feature/Livewire/Pages/Auth/RegistrationTest.php
Labels: i18n, front, livewire

#251 feat:[LAR-141] fix edit tage name on admin panel
  app/Filament/Resources/TagResource.php
  composer.lock
  public/css/filament/filament/app.css
Labels: php

#254 feat:[lar-139] transfert notification page to livewire page
  app/Livewire/Pages/Notifications.php
  resources/views/livewire/notifications-page.blade.php
  resources/views/livewire/pages/notifications.blade.php
  resources/views/user/notifications.blade.php
  routes/web.php
Labels: front

#253 wip: [LAR-112] discussion comment feature
  app/Actions/Replies/CreateReply.php
  app/Actions/Replies/LikeReply.php
  app/Livewire/Components/Discussion/Comment.php
  app/Livewire/Components/Discussion/Comments.php
  app/Livewire/Discussions/AddComment.php
  app/Livewire/Discussions/Comment.php
  app/Livewire/Discussions/Comments.php
  app/Livewire/Pages/Account/Profile.php
  app/Livewire/Pages/Discussions/SingleDiscussion.php
  app/Policies/ReplyPolicy.php
  composer.json
  composer.lock
  lang/en/global.php
  lang/en/notifications.php
  lang/en/pages/discussion.php
  lang/fr/global.php
  lang/fr/notifications.php
  lang/fr/pages/discussion.php
  resources/views/components/layouts/header.blade.php
  resources/views/components/skeleton.blade.php
  resources/views/components/skeletons/comment.blade.php
  resources/views/discussions/edit.blade.php
  resources/views/discussions/new.blade.php
  resources/views/livewire/components/discussion/comment.blade.php
  resources/views/livewire/components/discussion/comments.blade.php
  resources/views/livewire/discussions/add-comment.blade.php
  resources/views/livewire/discussions/comment.blade.php
  resources/views/livewire/discussions/comments.blade.php
  resources/views/livewire/pages/discussions/single-discussion.blade.php
Labels: i18n, livewire

#252 feat:[lar-140] Remove point after deleted article ,thread and discussion
  app/Actions/Discussion/DeleteDiscussionAction.php
  app/Actions/Forum/DeleteThreadAction.php
  app/Livewire/Pages/Discussions/SingleDiscussion.php
  app/Livewire/Pages/Forum/DetailThread.php
  composer.lock
  tests/Feature/Livewire/Components/Slideovers/DiscussionFormTest.php
  tests/Feature/Livewire/Components/Slideovers/ThreadFormTest.php
  tests/Feature/Livewire/Pages/Discussion/SingleDiscussionTest.php
  tests/Feature/Livewire/Pages/Forum/DetailThreadTest.php
Labels: Improvement, front

#255 fix:[lar-135] fix blank slideover when user are not authenticate and …
  app/Livewire/Pages/Forum/Index.php
  resources/views/livewire/pages/forum/index.blade.php
Labels: bug, front

#256 feat: [LAR-131] update locale selector
  app/Actions/Discussion/ConvertDiscussionToThreadAction.php
  app/Actions/Discussion/CreateDiscussionReplyAction.php
  app/Actions/Discussion/LikeReplyAction.php
  app/Actions/Discussion/NotifyUsersOfThreadConversionAction.php
  app/Http/Controllers/SubscriptionController.php
  app/Livewire/Components/ChangeLocale.php
  app/Livewire/Components/Discussion/Comment.php
  app/Livewire/Components/Discussion/Comments.php
  app/Livewire/Components/Slideovers/ArticleForm.php
  app/Livewire/Pages/Articles/Index.php
  app/Livewire/Pages/Articles/SingleTag.php
  app/Livewire/Pages/Discussions/Index.php
  app/Livewire/Pages/Forum/Index.php
  app/Models/Article.php
  app/Models/Channel.php
  app/Models/Discussion.php
  app/Models/Enterprise.php
  app/Models/Reply.php
  app/Models/Scopes/LocaleScope.php
  app/Models/Tag.php
  app/Models/Thread.php
  app/Models/Traits/HasAuthor.php
  app/Models/Traits/HasLocaleScope.php
  app/Models/Traits/HasReplies.php
  app/Models/Traits/HasSlug.php
  app/Notifications/ArticleSubmitted.php
  app/Notifications/NewCommentNotification.php
  app/Notifications/PostArticleToTelegram.php
  app/Notifications/PostArticleToTwitter.php
  app/Notifications/PostDiscussionToTelegram.php
  app/Spotlight/Article.php
  app/Spotlight/Discussion.php
  app/Spotlight/Sujet.php
  app/Traits/WithLocale.php
  app/helpers.php
  phpstan.neon
  resources/views/components/articles/card-author.blade.php
  resources/views/components/discussions/summary.blade.php
  resources/views/components/feeds/created_reply.blade.php
  resources/views/components/locale-selector.blade.php
  resources/views/components/tag.blade.php
  resources/views/emails/new_reply.blade.php
  resources/views/livewire/components/slideovers/article-form.blade.php
  resources/views/livewire/pages/articles/index.blade.php
  resources/views/livewire/pages/articles/tag.blade.php
  resources/views/livewire/pages/discussions/index.blade.php
  resources/views/livewire/pages/forum/index.blade.php
  resources/views/user/dashboard.blade.php
  tests/Feature/Forum/DiscussionTest.php
  tests/Feature/Forum/ThreadTest.php
Labels: bug, Improvement, front

#258 feat:[LAR-134] Refactor edit and create thread to action and write test
  app/Actions/Forum/CreateThreadAction.php
  app/Actions/Forum/UpdateThreadAction.php
  app/Livewire/Components/Slideovers/ThreadForm.php
  tests/Feature/Actions/Forum/CreateThreadActionTest.php
  tests/Feature/Actions/Forum/UpdateThreadActionTest.php
Labels: front, livewire

#257 lar:[137] change notification count and indicator to volt component
  app/Livewire/NotificationCount.php
  app/Livewire/NotificationIndicator.php
  resources/views/livewire/notification-count.blade.php
  resources/views/livewire/notification-indicator.blade.php
  tests/Feature/Livewire/Components/NotificationCountTest.php
  tests/Feature/Livewire/Components/NotificationIndicatorTest.php
Labels: front, livewire

#259 feat:(LAR-89) add tracking for user
  app/Http/Middleware/TrackLastActivity.php
  app/Models/User.php
  bootstrap/app.php
  composer.lock
  database/migrations/2024_12_19_234550_add_last_active_at_to_users_table.php
  tests/Feature/UserActivitiesTest.php
Labels: Ready to review, php

#262 feat: [LAR-106] add github repositories on the homepage
  .env.example
  app/Actions/GetGithubRepositoriesAction.php
  app/Data/RepositoryData.php
  config/services.php
  lang/en/global.php
  lang/fr/global.php
  resources/views/components/repository.blade.php
  resources/views/home.blade.php
  resources/views/livewire/components/discussion/comment.blade.php
  resources/views/livewire/components/github-repositories.blade.php
  resources/views/livewire/markdown-x.blade.php
Labels: front, Ready to review, api

#263 Feature/lar 14 update communities links
  app/Http/Controllers/DiscussionController.php
  app/Http/Controllers/FileUploadController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/SlackController.php
  app/Http/Requests/Api/UpdatePasswordRequest.php
  app/Http/Requests/Api/UpdateProfileRequest.php
  app/Livewire/Pages/Forum/Index.php
  app/Livewire/Pages/Home.php
  app/Models/Discussion.php
  app/Models/User.php
  app/Providers/EventServiceProvider.php
  app/helpers.php
  composer.json
  composer.lock
  config/livewire.php
  lang/en/global.php
  lang/fr/global.php
  lang/fr/pages/home.php
  public/images/decoration.gif
  public/images/guirlande1.png
  public/images/guirlande2.png
  public/images/guirlande3.png
  public/images/themes/theme-dark.png
  public/images/themes/theme-light.png
  resources/views/components/icon/christmas-town.blade.php
  resources/views/components/icon/christmas-tree.blade.php
  resources/views/components/layouts/footer.blade.php
  resources/views/components/layouts/header.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/pages/discussions/index.blade.php
  resources/views/livewire/pages/home.blade.php
  resources/views/partials/_navigation.blade.php
  resources/views/slack.blade.php
  resources/views/user/settings/customization.blade.php
  routes/web.php
Labels: Improvement, i18n, front, Ready to review

#264 feat:[lar-143] Translate faq age
  lang/en/global.php
  lang/fr/global.php
  package-lock.json
  public/robots.txt
  resources/views/components/layouts/footer.blade.php
  resources/views/faq.blade.php
  routes/web.php
Labels: i18n, front

#261 feat:[LAR-85] add articles Approuved in sitemap
  .gitignore
  app/Actions/Article/ApprovedArticleAction.php
  app/Console/Commands/GenerateSitemap.php
  app/Console/Commands/Sitemap/GenerateArticlesSitemapCommand.php
  app/Console/Commands/Sitemap/GenerateDiscussionsSitemapCommand.php
  app/Filament/Resources/ArticleResource.php
  app/Livewire/Components/Discussion/Comments.php
  app/Models/Article.php
  app/Models/Discussion.php
  composer.json
  composer.lock
  public/sitemaps/.gitkeep
  routes/console.php
Labels: Improvement, front

#267 feat:[lar-145] complete preference page
  app/Livewire/Components/User/Preferences.php
  lang/en/global.php
  lang/fr/global.php
  resources/js/app.js
  resources/views/layouts/app.blade.php
  resources/views/livewire/components/user/preferences.blade.php
  resources/views/livewire/pages/account/settings.blade.php
Labels: i18n, front

#265 feat:[lar-144] translate about-us page and remove subscribe and unscu…
  app/Livewire/Discussions/Subscribe.php
  app/Livewire/Editor.php
  app/Livewire/MarkdownX.php
  lang/en/pages/about.php
  lang/fr/pages/about.php
  resources/views/about.blade.php
  resources/views/components/layouts/header.blade.php
  resources/views/livewire/components/notification-count.blade.php
  resources/views/livewire/components/notification-indicator.blade.php
  resources/views/livewire/components/user/notifications.blade.php
  resources/views/livewire/discussions/subscribe.blade.php
  resources/views/livewire/editor.blade.php
  resources/views/livewire/markdown-x.blade.php
  resources/views/livewire/pages/about.blade.php
  resources/views/livewire/pages/discussions/single-discussion.blade.php
  resources/views/livewire/pages/notifications.blade.php
  resources/views/pages/privacy.blade.php
  resources/views/pages/rules.blade.php
  resources/views/pages/terms.blade.php
  routes/web.php
  tests/Feature/Livewire/Components/NotificationCountTest.php
  tests/Feature/Livewire/Components/NotificationIndicatorTest.php
Labels: i18n, front

#268 feat: [LAR-22] update sponsoring page
  .env.example
  app/Http/Controllers/SponsoringController.php
  app/Livewire/Components/SponsorSubscription.php
  app/Livewire/Modals/AnonymousSponsors.php
  app/Livewire/Pages/Sponsoring.php
  app/Livewire/SponsorSubscription.php
  app/Models/Transaction.php
  config/lcm.php
  lang/en/notifications.php
  lang/en/pages/sponsoring.php
  lang/en/validation.php
  lang/fr/notifications.php
  lang/fr/pages/sponsoring.php
  lang/fr/validation.php
  resources/views/components/error-message.blade.php
  resources/views/components/join-sponsors.blade.php
  resources/views/components/modal.blade.php
  resources/views/components/notification.blade.php
  resources/views/components/sponsor-profile.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/components/sponsor-subscription.blade.php
  resources/views/livewire/modals/anonymous-sponsors.blade.php
  resources/views/livewire/pages/sponsoring.blade.php
  resources/views/livewire/sponsor-subscription.blade.php
  resources/views/sponsors/index.blade.php
  routes/web.php
Labels: i18n, front, Ready to review, livewire

#269 feat: [LAR-91] add google analtycs G4
  resources/views/partials/_analytics.blade.php
Labels: Ready to review

#270 fix:[lar-146] undefined name fix after payement
  app/Livewire/Components/SponsorSubscription.php
  lang/fr/pages/account.php
  resources/views/components/sponsor-profile.blade.php
  resources/views/livewire/pages/account/profile.blade.php
  routes/features/account.php
Labels: bug

#273 feat: [LAR-148] update avatar column on social account table
  database/migrations/2024_12_25_100659_update_avatar_column_on_social_accounts_table.php
Labels: Improvement, Ready to review

#272 docs: [LAR-147] update readme
  README.md
  app/Http/Controllers/NotchPayCallBackController.php
  database/seeders/Fixtures/ArticleTableSeeder.php
  database/seeders/Fixtures/ThreadTableSeeder.php
  resources/views/ads/ln.blade.php
  resources/views/livewire/pages/home.blade.php
Labels: Ready to review

#274 feat:[lar-35] add spotlight search
  app/Spotlight/Article.php
  app/Spotlight/Articles.php
  app/Spotlight/FAQs.php
  app/Spotlight/Slack.php
  app/Spotlight/Telegram.php
  config/livewire-ui-spotlight.php
  lang/vendor/livewire-ui-spotlight/en/spotlight.php
  lang/vendor/livewire-ui-spotlight/fr/spotlight.php
  resources/views/layouts/app.blade.php
  resources/views/vendor/livewire-ui-modal/modal.blade.php
  resources/views/vendor/livewire-ui-spotlight/.gitkeep
  resources/views/vendor/livewire-ui-spotlight/spotlight.blade.php
Labels: front

#277 fix: github connect url
  resources/views/partials/_socials-link.blade.php
Labels: Ready to review

#279 feat: [LAR-161] fix mobile responsive a remove unused files
  app/Livewire/Pages/Discussions/Index.php
  app/Livewire/Pages/Forum/Index.php
  resources/js/app.js
  resources/js/components/datepicker.js
  resources/js/components/internationalNumber.js
  resources/js/elements/TimeAgo.js
  resources/js/elements/TimeCountdown.js
  resources/js/elements/index.js
  resources/js/utils/dom.js
  resources/js/utils/header.js
  resources/js/utils/helpers.js
  resources/js/utils/timers.js
  resources/js/utils/window.js
  resources/views/components/articles/card.blade.php
  resources/views/components/discussions/overview.blade.php
  resources/views/components/forum/thread.blade.php
  resources/views/livewire/pages/articles/index.blade.php
  resources/views/livewire/pages/articles/tag.blade.php
  resources/views/livewire/pages/discussions/index.blade.php
  resources/views/livewire/pages/home.blade.php
Labels: front

#280 fix:[lar-162] translate text
  resources/views/components/user/articles.blade.php
  resources/views/livewire/components/slideovers/article-form.blade.php
Labels: bug, i18n, front

#281 MEP - merge develop into main
  app/Livewire/Pages/Discussions/Index.php
  app/Livewire/Pages/Forum/Index.php
  resources/js/app.js
  resources/js/components/datepicker.js
  resources/js/components/internationalNumber.js
  resources/js/elements/TimeAgo.js
  resources/js/elements/TimeCountdown.js
  resources/js/elements/index.js
  resources/js/utils/dom.js
  resources/js/utils/header.js
  resources/js/utils/helpers.js
  resources/js/utils/timers.js
  resources/js/utils/window.js
  resources/views/components/articles/card.blade.php
  resources/views/components/discussions/overview.blade.php
  resources/views/components/forum/thread.blade.php
  resources/views/components/user/articles.blade.php
  resources/views/livewire/components/slideovers/article-form.blade.php
  resources/views/livewire/pages/articles/index.blade.php
  resources/views/livewire/pages/articles/tag.blade.php
  resources/views/livewire/pages/discussions/index.blade.php
  resources/views/livewire/pages/home.blade.php
Labels: bug, i18n, front

#282 feat:[lar-163] translate page and remove unused files
  lang/en/pages/account.php
  lang/en/pages/article.php
  lang/en/pages/channel.php
  lang/en/pages/discussion.php
  lang/en/pages/forum.php
  lang/fr/pages/account.php
  lang/fr/pages/article.php
  lang/fr/pages/channel.php
  lang/fr/pages/discussion.php
  lang/fr/pages/forum.php
  resources/views/components/notifications/new_comment.blade.php
  resources/views/components/notifications/new_mention.blade.php
  resources/views/components/notifications/new_reply.blade.php
  resources/views/components/rules-banner.blade.php
  resources/views/livewire/components/forum/reply-form.blade.php
  resources/views/livewire/components/user/articles.blade.php
  resources/views/livewire/components/user/discussions.blade.php
  resources/views/livewire/components/user/notifications.blade.php
  resources/views/livewire/pages/forum/channels.blade.php
  resources/views/livewire/pages/notifications.blade.php
Labels: i18n, front

#286 feat:[lar-156] Add lazy loading in img
  resources/views/components/ads.blade.php
  resources/views/components/articles/card-author.blade.php
  resources/views/components/articles/card.blade.php
  resources/views/components/articles/overview.blade.php
  resources/views/components/discussions/overview.blade.php
  resources/views/components/dropdown-profile.blade.php
  resources/views/components/feeds/comment.blade.php
  resources/views/components/join-sponsors.blade.php
  resources/views/components/layouts/footer.blade.php
  resources/views/components/layouts/header.blade.php
  resources/views/components/profile-users.blade.php
  resources/views/components/sponsors.blade.php
  resources/views/components/user/avatar.blade.php
  resources/views/livewire/pages/about.blade.php
  resources/views/livewire/pages/articles/single-post.blade.php
  resources/views/livewire/pages/home.blade.php
  resources/views/livewire/pages/sponsoring.blade.php
  resources/views/livewire/reactions.blade.php
  resources/views/vendor/mail/html/header.blade.php
Labels: front

#287 fix: (LAR-154) fixing bug when displaying user thread suscription
  app/Http/Controllers/Api/Auth/RegisterController.php
  app/Livewire/Pages/Forum/Index.php
  app/Models/User.php
  app/Widgets/MostActiveUsersPerWeek.php
  composer.lock
  config/permission.php
  database/factories/ArticleFactory.php
  database/factories/UserFactory.php
Labels: bug, Ready to review

#288 feat: [LAR-164] add filament mails logger
  app/Providers/Filament/AdminPanelProvider.php
  composer.json
  composer.lock
  config/filament-mails.php
  config/mails.php
  database/migrations/2024_12_31_093231_1_create_mails_table.php
  database/migrations/2024_12_31_093232_2_create_mail_attachments_table.php
  database/migrations/2024_12_31_093233_2_create_mail_events_table.php
  database/migrations/2024_12_31_093234_2_create_mailables_table.php
Labels: Improvement, filament
