Repository laravelcm/laravel.cm, pull requests merged in 2024-11, with the labels that each got.

#171 feat: [LAR-28] add articles livewire page
  app/Actions/Article/CreateArticleAction.php
  app/Actions/Discussion/CreateDiscussionAction.php
  app/Data/CreateArticleData.php
  app/Data/CreateDiscussionData.php
  app/Http/Controllers/ArticlesController.php
  app/Livewire/Articles/Browse.php
  app/Livewire/Articles/Create.php
  app/Livewire/Discussions/Create.php
  app/Livewire/Pages/Articles/Index.php
  app/Livewire/Pages/Articles/SinglePost.php
  app/Livewire/Pages/Articles/SingleTag.php
  app/Models/Article.php
  app/Models/Tag.php
  app/Traits/ModelHelpers.php
  app/Traits/WithInfiniteScroll.php
  app/Traits/WithTags.php
  config/lcm.php
  lang/en/global.php
  lang/en/pages/article.php
  lang/fr/global.php
  lang/fr/pages/article.php
  resources/js/utils/helpers.js
  resources/views/ads/ln.blade.php
  resources/views/articles/index.blade.php
  resources/views/articles/show.blade.php
  resources/views/components/articles/card-author.blade.php
  resources/views/components/articles/card-with-author.blade.php
  resources/views/components/articles/card.blade.php
  resources/views/components/articles/filter.blade.php
  resources/views/components/articles/overview.blade.php
  resources/views/components/danger-button.blade.php
  resources/views/components/section-header.blade.php
  resources/views/components/sponsors.blade.php
  resources/views/components/tag.blade.php
  resources/views/components/view-mode.blade.php
  resources/views/components/winter-is-coming.blade.php
  resources/views/home.blade.php
  resources/views/livewire/articles/browse.blade.php
  resources/views/livewire/pages/articles/index.blade.php
  resources/views/livewire/pages/articles/single-post.blade.php
  resources/views/livewire/pages/articles/tag.blade.php
  resources/views/livewire/pages/forum/detail-thread.blade.php
  routes/web.php
  tests/Feature/Actions/Article/CreateArticleActionTest.php
  tests/Feature/Actions/Discussion/CreateDiscussionActionTest.php
Labels: Ready to review

#208 fix: (LAR-21) resolve sharing article into twitter
  .env.example
  app/Console/Commands/PostArticleToTwitter.php
  composer.json
  composer.lock
  config/services.php
  tests/Feature/Article/PostArticleToTwitterTest.php
Labels: bug, Improvement, Ready to review

#209 feat: [LAR-100] add create and update articles
  app/Actions/Article/CreateArticleAction.php
  app/Data/CreateArticleData.php
  app/Filament/Resources/ArticleResource.php
  app/Gamify/Points/ArticlePublished.php
  app/Http/Controllers/ArticlesController.php
  app/Livewire/Articles/Create.php
  app/Livewire/Articles/Edit.php
  app/Livewire/Components/Slideovers/ArticleForm.php
  app/Livewire/Components/Slideovers/ThreadForm.php
  app/Livewire/Modals/DeleteReply.php
  app/Livewire/Modals/DeleteThread.php
  app/Livewire/Pages/Articles/Index.php
  app/Livewire/Pages/Articles/SinglePost.php
  app/Models/Article.php
  app/Models/Builders/ArticleQueryBuilder.php
  app/Policies/ArticlePolicy.php
  app/Policies/DiscussionPolicy.php
  app/Policies/ThreadPolicy.php
  composer.json
  composer.lock
  lang/en/global.php
  lang/en/notifications.php
  lang/en/pages/article.php
  lang/en/pages/forum.php
  lang/fr/global.php
  lang/fr/notifications.php
  lang/fr/pages/article.php
  lang/fr/pages/forum.php
  package.json
  resources/js/app.js
  resources/views/articles/edit.blade.php
  resources/views/articles/new.blade.php
  resources/views/components/articles/card-author.blade.php
  resources/views/components/articles/card.blade.php
  resources/views/components/launch-content.blade.php
  resources/views/components/layouts/header.blade.php
  resources/views/components/torchlight.blade.php
  resources/views/livewire/articles/_form.blade.php
  resources/views/livewire/articles/create.blade.php
  resources/views/livewire/articles/edit.blade.php
  resources/views/livewire/components/slideovers/article-form.blade.php
  resources/views/livewire/modals/delete-reply.blade.php
  resources/views/livewire/modals/unsplash.blade.php
  resources/views/livewire/pages/articles/single-post.blade.php
  resources/views/partials/_navigation.blade.php
  routes/features/article.php
  tests/Feature/Actions/Article/CreateArticleActionTest.php
  tests/Feature/Article/SendTelegramNotificationTest.php
  tests/Feature/Filament/ArticleTest.php
  tests/Feature/Livewire/Components/Slideovers/ArticleFormTest.php
Labels: Ready to review

#215 Feature/lar 109 echappement de code dans le mail de notification
  composer.lock
  resources/views/emails/new_reply.blade.php
  resources/views/vendor/mail/html/layout.blade.php
Labels: bug

#217 fix: (LAR-114) fix welcome message
  package-lock.json
  resources/views/emails/welcome.blade.php
Labels: bug

#219 feat: [LAR-110] listing and detail of discussions
  app/Console/Commands/PublishArticles.php
  app/Http/Controllers/DiscussionController.php
  app/Livewire/Discussions/Browse.php
  app/Livewire/Pages/Discussions/Index.php
  app/Livewire/Pages/Discussions/SingleDiscussion.php
  app/Models/Feature.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/Traits/HasSlug.php
  app/Traits/WithArticleAttributes.php
  app/Traits/WithChannelsAssociation.php
  app/Traits/WithTags.php
  app/View/Composers/InactiveDiscussionsComposer.php
  app/View/Composers/ModeratorsComposer.php
  app/View/Composers/ProfileUsersComposer.php
  app/View/Composers/TopContributorsComposer.php
  app/View/Composers/TopMembersComposer.php
  app/Widgets/MostActiveUsersPerWeek.php
  app/Widgets/MostLikedPostsPerWeek.php
  app/Widgets/MostViewedPostsPerWeek.php
  app/Widgets/RecentNumbers.php
  app/Widgets/RecentPostsPerWeek.php
  composer.lock
  lang/en/global.php
  lang/fr/global.php
  lang/fr/pages/discussion.php
  resources/views/components/discussions/overview.blade.php
  resources/views/components/scrollable-content.blade.php
  resources/views/components/tag.blade.php
  resources/views/components/tags.blade.php
  resources/views/components/user/status.blade.php
  resources/views/discussions/_contributions.blade.php
  resources/views/discussions/index.blade.php
  resources/views/discussions/show.blade.php
  resources/views/livewire/discussions/add-comment.blade.php
  resources/views/livewire/discussions/browse.blade.php
  resources/views/livewire/discussions/comment.blade.php
  resources/views/livewire/discussions/comments.blade.php
  resources/views/livewire/pages/discussions/index.blade.php
  resources/views/livewire/pages/discussions/single-discussion.blade.php
  resources/views/partials/_contributions.blade.php
  resources/views/partials/_leading-addons.blade.php
  routes/features/discussion.php
  routes/web.php
Labels: i18n, front, Ready to review, livewire

#220 fix: [LAR-116] publish scope on single tag articles list
  app/Livewire/Pages/Articles/SingleTag.php
  resources/views/components/articles/card-author.blade.php
Labels: bug, Ready to review

#221 fix (LAR-107) correction du fichier verify-email
  app/Filament/Resources/ArticleResource.php
  app/Http/Requests/UpdatePasswordRequest.php
  app/Livewire/Components/Forum/Reply.php
  app/Livewire/Components/Slideovers/ArticleForm.php
  app/Livewire/Modals/ApprovedArticle.php
  app/Livewire/Modals/DeleteArticle.php
  app/Livewire/Modals/DeleteDiscussion.php
  app/Livewire/Pages/Forum/Index.php
  app/Models/Reply.php
  app/Notifications/SendApprovedArticle.php
  app/Policies/ArticlePolicy.php
  app/Spotlight/Discussion.php
  phpstan.neon
  resources/views/components/forum/filters.blade.php
  resources/views/components/forum/thread-author.blade.php
  resources/views/components/forum/thread-summary.blade.php
  resources/views/components/scripts.blade.php
  resources/views/components/user/articles.blade.php
  resources/views/components/user/discussions.blade.php
  resources/views/components/user/threads.blade.php
  resources/views/cpanel/users/index.blade.php
  resources/views/layouts/settings.blade.php
  resources/views/livewire/components/channels-selector.blade.php
  resources/views/livewire/discussions/subscribe.blade.php
  resources/views/livewire/modals/anonymous-sponsors.blade.php
  resources/views/livewire/modals/approved-article.blade.php
  resources/views/livewire/modals/delete-article.blade.php
  resources/views/livewire/modals/delete-discussion.blade.php
  resources/views/livewire/pages/auth/forgot-password.blade.php
  resources/views/livewire/pages/auth/register.blade.php
  resources/views/livewire/pages/auth/reset-password.blade.php
  resources/views/livewire/pages/auth/verify-email.blade.php
  resources/views/livewire/sponsor-subscription.blade.php
  resources/views/slack.blade.php
  resources/views/sponsors/index.blade.php
  resources/views/user/profile.blade.php
  resources/views/user/settings/password.blade.php
  resources/views/user/settings/profile.blade.php
  resources/views/user/threads.blade.php
  tests/Feature/Auth/AuthenticationTest.php
  tests/Feature/Auth/PasswordConfirmationTest.php
  tests/Feature/Auth/PasswordResetTest.php
  tests/Feature/Auth/PasswordUpdateTest.php
  tests/Feature/Auth/RegistrationTest.php
  tests/Feature/Filament/ArticleResourceTest.php
Labels: bug

#222 fea: (LAR-87) Mise en place des test pour la signalisation d'un contenu
  app/Actions/ReportSpamAction.php
  app/Contracts/SpamReportableContract.php
  app/Exceptions/CanReportSpamException.php
  app/Livewire/ReportSpam.php
  app/Models/Discussion.php
  app/Models/Reply.php
  app/Models/SpamReport.php
  app/Models/Thread.php
  app/Models/User.php
  app/Notifications/ArticleSubmitted.php
  app/Notifications/ReportedSpamToTelegram.php
  app/Policies/DiscussionPolicy.php
  app/Policies/ReplyPolicy.php
  app/Policies/ThreadPolicy.php
  app/Traits/HasSpamReports.php
  composer.lock
  database/factories/RoleFactory.php
  database/migrations/2024_11_13_155231_create_spam_reports_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/FeatureTableSeeder.php
  lang/en/notifications.php
  lang/fr/notifications.php
  phpstan.neon
  resources/css/filament/admin/tailwind.config.js
  resources/views/livewire/components/forum/reply.blade.php
  resources/views/livewire/components/report-spam.blade.php
  resources/views/livewire/pages/forum/detail-thread.blade.php
  tailwind.config.js
  tests/Feature/Actions/ReportSpamActionTest.php
  tests/Feature/Article/SendTelegramNotificationTest.php
  tests/Feature/BasicArchitectureTest.php
  tests/Feature/Livewire/ReportSpamTest.php
Labels: Improvement, i18n, front, livewire
