Repository laravelcm/laravel.cm, pull requests merged in 2024-10, with the labels that each got.

#147 feat: sending notification after creation of a discussion
  .gitignore
  .phpunit.cache/test-results
  app/Actions/Discussion/CreateDiscussionAction.php
  app/Data/Discussion/CreateDiscussionData.php
  app/Livewire/Discussions/Create.php
  app/Models/Discussion.php
  app/Traits/WithTagsAssociation.php
  composer.json
  composer.lock
  config/livewire.php
  phpunit.xml
  resources/views/livewire/markdown-x.blade.php
  src/Domain/Enterprise/.gitkeep
  src/Domain/Forum/.gitkeep
  src/Domain/Job/.gitkeep
  src/Domain/Profile/.gitkeep
  src/Domain/Sponsor/.gitkeep
  src/Domain/Subscription/.gitkeep
  tests/CreatesApplication.php
  tests/Feature/Actions/.gitkeep
  tests/Feature/Actions/Discussion/CreateDiscussionActionTest.php
  tests/Feature/Livewire/DiscussionTest.php
  tests/TestCase.php
Labels: Ready to review

#159 fix(LAR-73): failed tests
  app/Actions/Replies/CreateReply.php
  app/Actions/Replies/LikeReply.php
  app/Livewire/Discussions/AddComment.php
  app/Livewire/Discussions/Comment.php
  app/Livewire/MarkdownX.php
  app/Models/User.php
  composer.lock
  phpstan.neon
  resources/views/livewire/articles/_form.blade.php
  resources/views/livewire/articles/create.blade.php
  resources/views/livewire/discussions/_form.blade.php
  resources/views/livewire/discussions/create.blade.php
  resources/views/livewire/forum/_form.blade.php
Labels: Ready to review

#161 feat: (LAR-83) improve SEO, remove unecessary links
  app/Console/Commands/GenerateSitemap.php
  app/Providers/RouteServiceProvider.php
  composer.lock
  public/robots.txt
  resources/views/components/discord.blade.php
  resources/views/faq.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/sponsors/index.blade.php
  resources/views/vendor/mail/html/footer.blade.php
  routes/web.php
Labels: enhancement, feature, Ready to review

#163 feat:[LAR-70] Add discussions table in admin cpanel and add feature t…
  app/Filament/Resources/DiscussionResource.php
  app/Filament/Resources/DiscussionResource/Pages/ListDiscussions.php
  tests/Feature/Filament/DiscussionTest.php
Labels: feature, Ready to review
