Repository laravelcm/laravel.cm, pull requests merged in 2025-01, with the labels that each got.

#289 feat: [LAR-150] add forum leaderboard page
  app/Livewire/Components/Reactions.php
  app/Livewire/Components/ReportSpam.php
  app/Livewire/Pages/Forum/Index.php
  app/Livewire/Pages/Forum/Leaderboard.php
  app/Models/User.php
  app/View/Composers/TopMembersComposer.php
  lang/en/global.php
  lang/en/pages/forum.php
  lang/fr/global.php
  lang/fr/pages/forum.php
  resources/css/app.css
  resources/css/file-upload.css
  resources/css/forum.css
  resources/css/toc.css
  resources/views/components/forum/leader.blade.php
  resources/views/components/forum/thread.blade.php
  resources/views/components/icon/trophies/first.blade.php
  resources/views/components/icon/trophies/second.blade.php
  resources/views/components/icon/trophies/third.blade.php
  resources/views/layouts/forum.blade.php
  resources/views/livewire/components/forum/reply.blade.php
  resources/views/livewire/components/reactions.blade.php
  resources/views/livewire/pages/discussions/single-discussion.blade.php
  resources/views/livewire/pages/forum/detail-thread.blade.php
  resources/views/livewire/pages/forum/index.blade.php
  resources/views/livewire/pages/forum/leaderboard.blade.php
  routes/features/forum.php
  tailwind.config.js
  tests/Feature/Livewire/ReportSpamTest.php
Labels: i18n, front, Ready to review, livewire

#291 chore: [LAR-168] fix layout of leaderboard when user is guest
  resources/views/layouts/forum.blade.php
Labels: bug

#295 fix: [LAR-172] article and discussion single page preview for seo
  app/Livewire/Pages/Articles/SinglePost.php
  app/Livewire/Pages/Discussions/SingleDiscussion.php
  app/Livewire/Pages/Home.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/View/Composers/InactiveDiscussionsComposer.php
  app/View/Composers/TopContributorsComposer.php
  composer.json
  composer.lock
  resources/views/layouts/app.blade.php
Labels: bug, front

#299 fix: [LAR-177] current locale bug
  app/Livewire/Components/ChangeLocale.php
Labels: bug

#302 MEP | merge develop into main
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Livewire/Components/ChangeLocale.php
  app/Livewire/Pages/Articles/SinglePost.php
  app/Livewire/Pages/Discussions/SingleDiscussion.php
  app/Livewire/Pages/Home.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/View/Composers/InactiveDiscussionsComposer.php
  app/View/Composers/TopContributorsComposer.php
  composer.json
  composer.lock
  lang/en/actions.php
  lang/fr/actions.php
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
  public/js/filament/forms/components/color-picker.js
  public/js/filament/forms/components/file-upload.js
  public/js/filament/forms/components/rich-editor.js
  resources/views/layouts/app.blade.php
Labels: Ready to review

#304 fix:[lar-179] hash password in register and add wire loading
  resources/views/livewire/pages/auth/register.blade.php
Labels: bug, front

#303 fix:[lar-169] mail bug for ThreadConverted
  app/Notifications/ThreadConvertedByCreator.php
Labels: bug

#306 feat:(LAR-171) BO add Stat in dashboard
  app/Filament/Resources/ArticleResource/Widgets/ArticleStatsOverview.php
  app/Filament/Resources/ArticleResource/Widgets/MostLikedPostsChart.php
  app/Filament/Resources/ArticleResource/Widgets/MostViewedPostsChart.php
  app/Filament/Resources/UserResource/Widgets/UserActivityWidget.php
  app/Filament/Resources/UserResource/Widgets/UserChartWidget.php
  app/Filament/Resources/UserResource/Widgets/UserStatsOverview.php
  app/Providers/Filament/AdminPanelProvider.php
  app/Widgets/MostActiveUsersPerWeek.php
  app/Widgets/MostLikedPostsPerWeek.php
  app/Widgets/MostViewedPostsPerWeek.php
  app/Widgets/RecentNumbers.php
  app/Widgets/RecentPostsPerWeek.php
  composer.json
  composer.lock
  resources/views/widgets/most_active_users_per_week.blade.php
  resources/views/widgets/most_liked_posts_per_week.blade.php
  resources/views/widgets/most_viewed_posts_per_week.blade.php
  resources/views/widgets/recent_numbers.blade.php
  resources/views/widgets/recent_posts_per_week.blade.php
Labels: Improvement, Ready to review

#307 feat:[LAR-171] limit number of article
  app/Filament/Resources/ArticleResource/Widgets/MostLikedPostsChart.php
  app/Filament/Resources/ArticleResource/Widgets/MostViewedPostsChart.php
  app/Filament/Resources/UserResource/Widgets/UserChartWidget.php
Labels: Improvement, Ready to review

#312 feat:(LAR-180) ajout des reaction et scroll sur article
  app/Livewire/Pages/Articles/Index.php
  resources/views/livewire/pages/articles/index.blade.php
  resources/views/livewire/pages/articles/single-post.blade.php
Labels: Improvement, Ready to review

#314 feat:(LAR-165) add filter for popular topics
  app/Livewire/Pages/Articles/Index.php
  app/Livewire/Pages/Forum/Index.php
  resources/views/layouts/forum.blade.php
  resources/views/livewire/pages/articles/index.blade.php
Labels: Improvement, Ready to review

#313 Feature/lar 152 sponsoring thanks mail
  app/Filament/Resources/ArticleResource.php
  app/Listeners/SendPaymentNotification.php
  app/Livewire/Components/SponsorSubscription.php
  app/Mail/SendSponsorThanksMail.php
  composer.lock
  lang/en/emails/sponsor.php
  lang/fr/emails/sponsor.php
  package-lock.json
  resources/views/emails/send-sponsor-thanks-mail.blade.php
Labels: Improvement, front

#316 fix:lar-178 profile link
  .gitignore
  resources/views/components/layouts/header.blade.php
  routes/features/account.php
Labels: bug

#317 fix:[lar-180] fix style in profile questions tabs
  app/Livewire/Components/User/Activities.php
  app/Livewire/Pages/Account/Profile.php
  composer.lock
  resources/views/components/forum/thread.blade.php
  resources/views/components/user/articles.blade.php
  resources/views/components/user/discussions.blade.php
  resources/views/components/user/threads.blade.php
  resources/views/layouts/forum.blade.php
  resources/views/livewire/components/reactions.blade.php
  resources/views/livewire/components/user/activities.blade.php
  resources/views/livewire/pages/account/profile.blade.php
  resources/views/livewire/pages/articles/single-post.blade.php
  resources/views/livewire/pages/forum/index.blade.php
Labels: bug

#323 feat: disabled default local for seo improve and eager loading model …
  app/Actions/Forum/CreateThreadAction.php
  app/Livewire/Pages/Articles/Index.php
  app/Livewire/Pages/Discussions/Index.php
  app/Livewire/Pages/Forum/Index.php
  app/Livewire/Pages/Forum/Leaderboard.php
  app/Models/Activity.php
  app/Models/Traits/HasLocaleScope.php
  resources/views/components/discussions/overview.blade.php
  resources/views/components/forum/thread.blade.php
  resources/views/components/user/discussions.blade.php
  resources/views/components/user/threads.blade.php
Labels: Improvement, Ready to review
